### ISSUE TITLE
Transition Layer Kernel Size

### ISSUE THREAD

**Issue by gosaindhruv** [bobo0810/S4ND_Pytorch#2]
Hi,

Have you used 3x3x3 kernel in your transition layer for a purpose since in your comments you have mentioned 1x1x1 kernel size.

**Comment by bobo0810** [comment]
> Hi,
> 
> Have you used 3x3x3 kernel in your transition layer for a purpose since in your comments you have mentioned 1x1x1 kernel size.

S4ND_Pytorch/imgs/network.png      detailed description of all network structures
